
package actividad4.codigo.isaiquispeperez.GUI;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaEjercicio3 extends javax.swing.JPanel {

    public VentanaEjercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        PanelEjercicio1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textTemperatura = new javax.swing.JTextField();
        textTiempo = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnEjemplo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        limpiarTablaSimulacion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFinal = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnEvaluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        textCampos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaConclusion = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        textX1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textX2 = new javax.swing.JTextField();
        btnCrearTabla = new javax.swing.JButton();

        PanelEjercicio1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EJERCICIO 3 - REACCION QUIMICA");

        jLabel10.setText("-------------------------------------------------");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("DATOS");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setText("Temperatua (grados)");

        jLabel9.setText("Tiempo (segundos)");

        textTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTemperaturaActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnEjemplo.setText("Ejercicio de Ejemplo");
        btnEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemploActionPerformed(evt);
            }
        });

        jLabel7.setText("TABLA DE SIMULACION");

        limpiarTablaSimulacion.setText("Limpiar tabla de simulacion");
        limpiarTablaSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTablaSimulacionActionPerformed(evt);
            }
        });

        tablaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Temperatura", "Tiempo", "X1", "X2", "Rendimiento"
            }
        ));
        jScrollPane2.setViewportView(tablaFinal);
        if (tablaFinal.getColumnModel().getColumnCount() > 0) {
            tablaFinal.getColumnModel().getColumn(0).setResizable(false);
            tablaFinal.getColumnModel().getColumn(2).setResizable(false);
        }

        btnLimpiar.setText("Vaciar Todo");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });

        jLabel4.setText("Campos");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel13.setText("Conclusion:");

        areaConclusion.setColumns(20);
        areaConclusion.setRows(5);
        jScrollPane3.setViewportView(areaConclusion);

        jLabel14.setText("X1");

        textX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textX1ActionPerformed(evt);
            }
        });

        jLabel15.setText("X2");

        btnCrearTabla.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCrearTabla.setText("CREAR TABLA");
        btnCrearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEjercicio1Layout = new javax.swing.GroupLayout(PanelEjercicio1);
        PanelEjercicio1.setLayout(PanelEjercicio1Layout);
        PanelEjercicio1Layout.setHorizontalGroup(
            PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEjercicio1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEjercicio1Layout.createSequentialGroup()
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnEjemplo))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(24, 24, 24)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textX1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(textX2)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnIngresar)
                                    .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textTiempo)
                                    .addComponent(textTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGenerar)))
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEjercicio1Layout.createSequentialGroup()
                                .addComponent(btnCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnLimpiar)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEvaluar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(limpiarTablaSimulacion))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        PanelEjercicio1Layout.setVerticalGroup(
            PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(limpiarTablaSimulacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEvaluar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnEjemplo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(16, 16, 16)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresar)
                            .addComponent(btnGenerar))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(10, 10, 10)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(textX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEjercicio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEjercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTemperaturaActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try{
            int temperatura = Integer.valueOf(textTemperatura.getText());
            int tiempo = Integer.valueOf(textTiempo.getText());
            
            double x1 = 0.0;
            double x2 = 0.0;
            
            double campos = 0.0;
            
            x1 = (temperatura-125.0)/10.0;
            x2 = (tiempo-300.0)/30.0;
            
            campos = 90.79-(1.095*x1)-(1.045*x2)-(2.781*Math.pow(x1, 2))-(2.524*Math.pow(x2, 2))-(0.755*x1*x2);
            
            x1 = Math.round(x1 * 100.0) / 100.0;
            x2 = Math.round(x2 * 100.0) / 100.0;
            campos = Math.round(campos * 100.0) / 100.0;
            
            textTemperatura.setText(String.valueOf(temperatura));
            textTiempo.setText(String.valueOf(tiempo));
            textX1.setText(String.valueOf(x1));
            textX2.setText(String.valueOf(x2));
            textCampos.setText(String.valueOf(campos));
            
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemploActionPerformed
        textTemperatura.setText(String.valueOf(100));
        textTiempo.setText(String.valueOf(300));
        
        textX1.setText(String.valueOf("-2.5"));
        textX2.setText(String.valueOf(0));
        
        textCampos.setText(String.valueOf(76.15));
    }//GEN-LAST:event_btnEjemploActionPerformed

    private void limpiarTablaSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTablaSimulacionActionPerformed
        DefaultTableModel modelFinal = (DefaultTableModel) tablaFinal.getModel();
        modelFinal.setRowCount(0);
    }//GEN-LAST:event_limpiarTablaSimulacionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        DefaultTableModel modelFinal = (DefaultTableModel) tablaFinal.getModel();

        modelFinal.setRowCount(0);

        areaConclusion.setText("");
        textTemperatura.setText(String.valueOf(""));
        textTiempo.setText(String.valueOf(""));
        textX1.setText("");
        textX2.setText("");
        textCampos.setText(String.valueOf(""));
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        try {
        DefaultTableModel model = (DefaultTableModel) tablaFinal.getModel();
        int rowCount = model.getRowCount();

        if (rowCount == 0) {
            JOptionPane.showMessageDialog(this, "La tabla está vacía.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double maxCampo = Double.MIN_VALUE;
        int maxRowIndex = -1;

        // Buscar el máximo en la última columna
        for (int i = 0; i < rowCount; i++) {
            double campo = Double.parseDouble(model.getValueAt(i, 4).toString());
            if (campo > maxCampo) {
                maxCampo = campo;
                maxRowIndex = i;
            }
        }

        // Obtener los valores de la fila donde se encontró el máximo
        int temperatura = Integer.parseInt(model.getValueAt(maxRowIndex, 0).toString());
        int tiempo = Integer.parseInt(model.getValueAt(maxRowIndex, 1).toString());
        double x1 = Double.parseDouble(model.getValueAt(maxRowIndex, 2).toString());
        double x2 = Double.parseDouble(model.getValueAt(maxRowIndex, 3).toString());

        // Formatear y mostrar el resultado en el área de texto
        String resultado = "La mejor manera de maximizar el ejercicio es con:\n" +
                           "Temperatura = " + temperatura + "\n" +
                           "Tiempo = " + tiempo + "\n" +
                           "x1 = " + x1 + "\n" +
                           "x2 = " + x2 + "\n" +
                           "Valor Maximizado = " + maxCampo;

        areaConclusion.setText(resultado);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al evaluar la tabla.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEvaluarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try {
             Random random = new Random();

            int temperatura = random.nextInt(120 - 30 + 1) + 30; // Números entre 30 y 120
            int tiempo = random.nextInt(500 - 50 + 1) + 50; // Números entre 50 y 500

            // Asignar los valores a los JTextField
            textTemperatura.setText(String.valueOf(temperatura));
            textTiempo.setText(String.valueOf(tiempo));
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void textX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textX1ActionPerformed

    private void btnCrearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaActionPerformed
        try {
            int temperatura = Integer.valueOf(textTemperatura.getText());
        int tiempo = Integer.valueOf(textTiempo.getText());

        double x1, x2, campos;

        int temperaturaMin = temperatura - 30;
        int temperaturaMax = temperatura + 30;
        int tiempoMin = tiempo - 50;
        int tiempoMax = tiempo + 50;

        DefaultTableModel model = (DefaultTableModel) tablaFinal.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de llenarla

        // Recorrer los valores de tiempo
        for (int t = tiempoMin; t <= tiempoMax; t += 5) {
            // Recorrer los valores de temperatura
            for (int temp = temperaturaMin; temp <= temperaturaMax; temp += 5) {
                x1 = (temp - 125.0) / 10.0;
                x2 = (t - 300.0) / 30.0;

                campos = 90.79 - (1.095 * x1) - (1.045 * x2) - (2.781 * Math.pow(x1, 2)) - 
                         (2.524 * Math.pow(x2, 2)) - (0.755 * x1 * x2);

                // Redondear valores
                x1 = Math.round(x1 * 100.0) / 100.0;
                x2 = Math.round(x2 * 100.0) / 100.0;
                campos = Math.round(campos * 100.0) / 100.0;

                // Agregar fila a la tabla
                model.addRow(new Object[]{temp, t, x1, x2, campos});
            }
        }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearTablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEjercicio1;
    private javax.swing.JTextArea areaConclusion;
    private javax.swing.JButton btnCrearTabla;
    private javax.swing.JButton btnEjemplo;
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpiarTablaSimulacion;
    private javax.swing.JTable tablaFinal;
    private javax.swing.JTextField textCampos;
    private javax.swing.JTextField textTemperatura;
    private javax.swing.JTextField textTiempo;
    private javax.swing.JTextField textX1;
    private javax.swing.JTextField textX2;
    // End of variables declaration//GEN-END:variables
}
