
package actividad5.tss.codigo.GUI;


import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class VentanaEjercicio1 extends javax.swing.JPanel {

    public VentanaEjercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PanelEjercicio1 = new javax.swing.JPanel();
        btnEjemplo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        caja1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        caja2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        caja3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        caja4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        caja5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        caja6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textPrecioVenta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textCosto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textPrecioDescuento = new javax.swing.JTextField();
        btnIngresarDatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGenerador = new javax.swing.JButton();
        btnCrearTabla = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaDistribuciones = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        limpiarTablaSimulacion = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla4 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabla5 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        tabla6 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaConclusion = new javax.swing.JTextArea();

        jLabel18.setText("---------------------------------------");

        setPreferredSize(new java.awt.Dimension(870, 540));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(1000, 800));

        PanelEjercicio1.setBackground(new java.awt.Color(102, 102, 102));
        PanelEjercicio1.setPreferredSize(new java.awt.Dimension(1500, 900));

        btnEjemplo.setText("Ejercicio de Ejemplo");
        btnEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemploActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EJERCICIO 1 - DULCE ADA");

        jLabel10.setText("-------------------------------------------------");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cantidades");

        jLabel8.setText("Cajas tabla 1:");

        caja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Cajas tabla 2:");

        caja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Cajas tabla 3:");

        caja3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja3ActionPerformed(evt);
            }
        });

        jLabel17.setText("Cajas tabla 4:");

        caja4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja4ActionPerformed(evt);
            }
        });

        jLabel30.setText("Cajas tabla 5:");

        caja5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja5ActionPerformed(evt);
            }
        });

        jLabel19.setText("Cajas tabla 6:");

        caja6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja6ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Parametros");

        jLabel9.setText("Precio de Venta:");

        jLabel14.setText("Costo:");

        textCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCostoActionPerformed(evt);
            }
        });

        jLabel16.setText("Precio con Descuento:");

        textPrecioDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioDescuentoActionPerformed(evt);
            }
        });

        btnIngresarDatos.setText("Ingresar");
        btnIngresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarDatosActionPerformed(evt);
            }
        });

        jLabel2.setText("O");

        btnGenerador.setText("Generar");
        btnGenerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneradorActionPerformed(evt);
            }
        });

        btnCrearTabla.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCrearTabla.setText("CREAR TABLAS");
        btnCrearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Vaciar Todo");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setText("DISTRIBUCION DE PROBABILIDADES");

        tablaDistribuciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Probabilidad", "Distr. Acumulada", "Rango Inferior", "Rango Superior", "Programas vendidos"
            }
        ));
        jScrollPane9.setViewportView(tablaDistribuciones);

        jLabel15.setText("Conclusion:");

        jLabel7.setText("TABLAS DE SIMULACION");

        limpiarTablaSimulacion.setText("Limpiar tablas de simulacion");
        limpiarTablaSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarTablaSimulacionActionPerformed(evt);
            }
        });

        jLabel21.setText("TABLA 1");

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REPLICA", "V. ALEATORIA", "DEMANDA", "GANANCIA"
            }
        ));
        jScrollPane2.setViewportView(tabla1);

        jLabel22.setText("TABLA 3");

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REPLICA", "V. ALEATORIA", "DEMANDA", "GANANCIA"
            }
        ));
        jScrollPane5.setViewportView(tabla2);

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REPLICA", "V. ALEATORIA", "DEMANDA", "GANANCIA"
            }
        ));
        jScrollPane7.setViewportView(tabla3);

        jLabel23.setText("TABLA 4");

        tabla4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REPLICA", "V. ALEATORIA", "DEMANDA", "GANANCIA"
            }
        ));
        jScrollPane6.setViewportView(tabla4);

        tabla5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REPLICA", "V. ALEATORIA", "DEMANDA", "GANANCIA"
            }
        ));
        jScrollPane8.setViewportView(tabla5);

        tabla6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REPLICA", "V. ALEATORIA", "DEMANDA", "GANANCIA"
            }
        ));
        jScrollPane11.setViewportView(tabla6);

        jLabel25.setText("TABLA 5");

        jLabel26.setText("TABLA 6");

        jLabel24.setText("TABLA 2");

        areaConclusion.setColumns(20);
        areaConclusion.setRows(5);
        jScrollPane1.setViewportView(areaConclusion);

        javax.swing.GroupLayout PanelEjercicio1Layout = new javax.swing.GroupLayout(PanelEjercicio1);
        PanelEjercicio1.setLayout(PanelEjercicio1Layout);
        PanelEjercicio1Layout.setHorizontalGroup(
            PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(caja6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(caja3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(caja4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                                    .addComponent(jLabel30)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(caja5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                                .addComponent(btnIngresarDatos)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnGenerador))))
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(btnEjemplo))
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(btnCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(btnLimpiar)))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEjercicio1Layout.createSequentialGroup()
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelEjercicio1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelEjercicio1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textPrecioDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(limpiarTablaSimulacion))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel23)
                                .addGap(385, 385, 385)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26)
                                .addGap(145, 145, 145))
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(jLabel21)
                                .addGap(377, 377, 377)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addGap(147, 147, 147))))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        PanelEjercicio1Layout.setVerticalGroup(
            PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(23, 23, 23)))
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(limpiarTablaSimulacion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addComponent(btnEjemplo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(caja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(caja4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(caja5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(caja6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresarDatos)
                            .addComponent(jLabel2)
                            .addComponent(btnGenerador))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(textPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(textCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(textPrecioDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(PanelEjercicio1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1079, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemploActionPerformed
        caja1.setText(String.valueOf(40));
        caja2.setText(String.valueOf(50));
        caja3.setText(String.valueOf(60));
        caja4.setText(String.valueOf(70));
        caja5.setText(String.valueOf(80));
        caja6.setText(String.valueOf(90));
        
        textPrecioVenta.setText(String.valueOf(12.00));
        textCosto.setText(String.valueOf(7.50));
        textPrecioDescuento.setText(String.valueOf(6.00));
        
        DefaultTableModel modelDistribuciones = (DefaultTableModel) tablaDistribuciones.getModel();
        modelDistribuciones.setRowCount(0);
        
        modelDistribuciones.addRow(new Object[]{0.1667, 0.1667, 0, 0.1667,40});
        modelDistribuciones.addRow(new Object[]{0.1667, 0.3333, 0.1667, 0.3333,50});
        modelDistribuciones.addRow(new Object[]{0.1667, 0.5000, 0.3333, 0.5000,60});
        modelDistribuciones.addRow(new Object[]{0.1667, 0.6667, 0.5000, 0.6667,70});
        modelDistribuciones.addRow(new Object[]{0.1667, 0.8333, 0.6667, 0.8333,80});
        modelDistribuciones.addRow(new Object[]{0.1667, 1.0000, 0.8333, 1.0000,90});

    }//GEN-LAST:event_btnEjemploActionPerformed

    private void caja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja1ActionPerformed

    private void caja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja2ActionPerformed

    private void caja3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja3ActionPerformed

    private void caja4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja4ActionPerformed

    private void caja5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja5ActionPerformed

    private void caja6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja6ActionPerformed

    private void textCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCostoActionPerformed

    private void textPrecioDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrecioDescuentoActionPerformed

    private void btnIngresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarDatosActionPerformed
        try{
            int val1 = Integer.valueOf(caja1.getText());
            int val2 = Integer.valueOf(caja2.getText());
            int val3 = Integer.valueOf(caja3.getText());
            int val4 = Integer.valueOf(caja4.getText());
            int val5 = Integer.valueOf(caja5.getText());
            int val6 = Integer.valueOf(caja6.getText());
            
            DefaultTableModel modelDistribuciones = (DefaultTableModel) tablaDistribuciones.getModel();
            modelDistribuciones.setRowCount(0);

            modelDistribuciones.addRow(new Object[]{0.1667, 0.1667, 0, 0.1667,val1});
            modelDistribuciones.addRow(new Object[]{0.1667, 0.3333, 0.1667, 0.3333,val2});
            modelDistribuciones.addRow(new Object[]{0.1667, 0.5000, 0.3333, 0.5000,val3});
            modelDistribuciones.addRow(new Object[]{0.1667, 0.6667, 0.5000, 0.6667,val4});
            modelDistribuciones.addRow(new Object[]{0.1667, 0.8333, 0.6667, 0.8333,val5});
            modelDistribuciones.addRow(new Object[]{0.1667, 1.0000, 0.8333, 1.0000,val6});
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarDatosActionPerformed

    private void btnGeneradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneradorActionPerformed
        try {
            // Asignar valores a los textFields
            caja1.setText(String.valueOf(generarRandom()));
            caja2.setText(String.valueOf(generarRandom()));
            caja3.setText(String.valueOf(generarRandom()));
            caja4.setText(String.valueOf(generarRandom()));
            caja5.setText(String.valueOf(generarRandom()));
            caja6.setText(String.valueOf(generarRandom()));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGeneradorActionPerformed

    private int generarRandom(){
        Random rand = new Random();
        int valor = (rand.nextInt(10) + 1) * 10;
        return valor;
    }
    
    private void btnCrearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaActionPerformed
        try {
            // Obtener modelos de todas las tablas
            DefaultTableModel modelDistribuciones = (DefaultTableModel) tablaDistribuciones.getModel();
            DefaultTableModel modelTabla1 = (DefaultTableModel) tabla1.getModel();
            DefaultTableModel modelTabla2 = (DefaultTableModel) tabla2.getModel();
            DefaultTableModel modelTabla3 = (DefaultTableModel) tabla3.getModel();
            DefaultTableModel modelTabla4 = (DefaultTableModel) tabla4.getModel();
            DefaultTableModel modelTabla5 = (DefaultTableModel) tabla5.getModel();
            DefaultTableModel modelTabla6 = (DefaultTableModel) tabla6.getModel();
            
            modelTabla1.setRowCount(0);
            modelTabla2.setRowCount(0);
            modelTabla3.setRowCount(0);
            modelTabla4.setRowCount(0);
            modelTabla5.setRowCount(0);
            modelTabla6.setRowCount(0);

            // Obtener valores de los textFields
            double precioVenta = Double.parseDouble(textPrecioVenta.getText());
            double costo = Double.parseDouble(textCosto.getText());
            double precioDescuento = Double.parseDouble(textPrecioDescuento.getText());

            int box1 = Integer.parseInt(caja1.getText());
            int box2 = Integer.parseInt(caja2.getText());
            int box3 = Integer.parseInt(caja3.getText());
            int box4 = Integer.parseInt(caja4.getText());
            int box5 = Integer.parseInt(caja5.getText());
            int box6 = Integer.parseInt(caja6.getText());

            Random rand = new Random();

            // Llenar cada tabla con 100 filas, pero con números aleatorios diferentes para cada una
            for (int i = 1; i <= 100; i++) {
                // Generar diferentes números aleatorios para cada tabla
                double numRandom1 = Math.round(rand.nextDouble() * 10000.0) / 10000.0;
                double numRandom2 = Math.round(rand.nextDouble() * 10000.0) / 10000.0;
                double numRandom3 = Math.round(rand.nextDouble() * 10000.0) / 10000.0;
                double numRandom4 = Math.round(rand.nextDouble() * 10000.0) / 10000.0;
                double numRandom5 = Math.round(rand.nextDouble() * 10000.0) / 10000.0;
                double numRandom6 = Math.round(rand.nextDouble() * 10000.0) / 10000.0;

                // Obtener la demanda según el número aleatorio para cada tabla
                int demanda1 = obtenerDemandaDesdeDistribuciones(numRandom1, modelDistribuciones);
                int demanda2 = obtenerDemandaDesdeDistribuciones(numRandom2, modelDistribuciones);
                int demanda3 = obtenerDemandaDesdeDistribuciones(numRandom3, modelDistribuciones);
                int demanda4 = obtenerDemandaDesdeDistribuciones(numRandom4, modelDistribuciones);
                int demanda5 = obtenerDemandaDesdeDistribuciones(numRandom5, modelDistribuciones);
                int demanda6 = obtenerDemandaDesdeDistribuciones(numRandom6, modelDistribuciones);

                // Calcular los resultados para cada tabla
                int resultado1 = calcularResultado(precioVenta, costo, precioDescuento, box1, demanda1);
                int resultado2 = calcularResultado(precioVenta, costo, precioDescuento, box2, demanda2);
                int resultado3 = calcularResultado(precioVenta, costo, precioDescuento, box3, demanda3);
                int resultado4 = calcularResultado(precioVenta, costo, precioDescuento, box4, demanda4);
                int resultado5 = calcularResultado(precioVenta, costo, precioDescuento, box5, demanda5);
                int resultado6 = calcularResultado(precioVenta, costo, precioDescuento, box6, demanda6);

                // Agregar las filas a cada tabla con sus propios valores
                modelTabla1.addRow(new Object[]{i, numRandom1, demanda1, resultado1});
                modelTabla2.addRow(new Object[]{i, numRandom2, demanda2, resultado2});
                modelTabla3.addRow(new Object[]{i, numRandom3, demanda3, resultado3});
                modelTabla4.addRow(new Object[]{i, numRandom4, demanda4, resultado4});
                modelTabla5.addRow(new Object[]{i, numRandom5, demanda5, resultado5});
                modelTabla6.addRow(new Object[]{i, numRandom6, demanda6, resultado6});
            }

            // Generar la conclusión
            generarConclusion(box1, box2, box3, box4, box5, box6, modelTabla1, modelTabla2, modelTabla3, modelTabla4, modelTabla5, modelTabla6);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearTablaActionPerformed

    // Método para obtener la demanda desde la tablaDistribuciones
    private int obtenerDemandaDesdeDistribuciones(double numeroRandom, DefaultTableModel modelDistribuciones) {
        for (int fila = 0; fila < modelDistribuciones.getRowCount(); fila++) {
            double limiteInferior = Double.parseDouble(modelDistribuciones.getValueAt(fila, 2).toString());
            double limiteSuperior = Double.parseDouble(modelDistribuciones.getValueAt(fila, 3).toString());

            if (numeroRandom >= limiteInferior && numeroRandom <= limiteSuperior) {
                return Integer.parseInt(modelDistribuciones.getValueAt(fila, 4).toString());
            }
        }
        return 0; // Si no se encuentra en los rangos, retorna 0
    }
    
    // Método para calcular el resultado de la cuarta columna en cada tabla
    private int calcularResultado(double precioVenta, double costo, double precioDescuento, int box, int demanda) {
        if (demanda <= box) {
            return (int) ((precioDescuento * demanda) - ((costo - precioDescuento) * box));
        } else {
            return (int) ((precioVenta * box) - (costo * box));
        }
    }
    
    // Método para generar la conclusión en el área de texto
    private void generarConclusion(int box1, int box2, int box3, int box4, int box5, int box6,
                                   DefaultTableModel modelTabla1, DefaultTableModel modelTabla2,
                                   DefaultTableModel modelTabla3, DefaultTableModel modelTabla4,
                                   DefaultTableModel modelTabla5, DefaultTableModel modelTabla6) {

        double promedio1 = calcularPromedio(modelTabla1);
        double promedio2 = calcularPromedio(modelTabla2);
        double promedio3 = calcularPromedio(modelTabla3);
        double promedio4 = calcularPromedio(modelTabla4);
        double promedio5 = calcularPromedio(modelTabla5);
        double promedio6 = calcularPromedio(modelTabla6);

        // Determinar cuál es el mayor promedio
        double[] promedios = {promedio1, promedio2, promedio3, promedio4, promedio5, promedio6};
        int[] cajas = {box1, box2, box3, box4, box5, box6};

        double maxPromedio = promedios[0];
        int mejorCaja = cajas[0];

        for (int i = 1; i < promedios.length; i++) {
            if (promedios[i] > maxPromedio) {
                maxPromedio = promedios[i];
                mejorCaja = cajas[i];
            }
        }

        // Construir el mensaje
        String mensaje = "RESULTADOS GENERALES\n" +
                         "COMPRA, GANANCIAS GENERALES\n" +
                         box1+" cajas" + ", promedio:" + promedio1 + "\n" +
                         box2+" cajas" + ", promedio:" + promedio2 + "\n" +
                         box3+" cajas" + ", promedio:" + promedio3 + "\n" +
                         box4+" cajas" + ", promedio:" + promedio4 + "\n" +
                         box5+" cajas" + ", promedio:" + promedio5 + "\n" +
                         box6+" cajas" + ", promedio:" + promedio6 + "\n\n" +
                         "La compra que más conviene es de:\n " +
                mejorCaja + " cajas, con un promedio de: " + maxPromedio+" $";

        // Mostrar en el área de texto
        areaConclusion.setText(mensaje);
    }

    // Método para calcular el promedio de la última columna de una tabla
    private double calcularPromedio(DefaultTableModel modelTabla) {
        double suma = 0;
        int filas = modelTabla.getRowCount();

        if (filas == 0) return 0; // Evitar división por cero

        for (int i = 0; i < filas; i++) {
            suma += Double.parseDouble(modelTabla.getValueAt(i, 3).toString());
        }

        return Math.round((suma / filas) * 100.0) / 100.0; // Redondear a 2 decimales
    }
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        DefaultTableModel modelDistribuciones = (DefaultTableModel) tablaDistribuciones.getModel();
        DefaultTableModel model1 = (DefaultTableModel) tabla1.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tabla2.getModel();
        DefaultTableModel model3 = (DefaultTableModel) tabla3.getModel();
        DefaultTableModel model4 = (DefaultTableModel) tabla4.getModel();
        DefaultTableModel model5 = (DefaultTableModel) tabla5.getModel();
        DefaultTableModel model6 = (DefaultTableModel) tabla6.getModel();
        

        modelDistribuciones.setRowCount(0);
        model1.setRowCount(0);
        model2.setRowCount(0);
        model3.setRowCount(0);
        model4.setRowCount(0);
        model5.setRowCount(0);
        model6.setRowCount(0);
        
        caja1.setText(String.valueOf(""));
        caja2.setText(String.valueOf(""));
        caja3.setText(String.valueOf(""));
        caja4.setText(String.valueOf(""));
        caja5.setText(String.valueOf(""));
        caja6.setText(String.valueOf(""));
        
        textPrecioVenta.setText(String.valueOf(""));
        textCosto.setText(String.valueOf(""));
        textPrecioDescuento.setText(String.valueOf(""));
        
        areaConclusion.setText(String.valueOf(""));
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void limpiarTablaSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarTablaSimulacionActionPerformed
        DefaultTableModel model1 = (DefaultTableModel) tabla1.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tabla2.getModel();
        DefaultTableModel model3 = (DefaultTableModel) tabla3.getModel();
        DefaultTableModel model4 = (DefaultTableModel) tabla4.getModel();
        DefaultTableModel model5 = (DefaultTableModel) tabla5.getModel();
        DefaultTableModel model6 = (DefaultTableModel) tabla6.getModel();
        
        model1.setRowCount(0);
        model2.setRowCount(0);
        model3.setRowCount(0);
        model4.setRowCount(0);
        model5.setRowCount(0);
        model6.setRowCount(0);
        
        areaConclusion.setText(String.valueOf(""));
    }//GEN-LAST:event_limpiarTablaSimulacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEjercicio1;
    private javax.swing.JTextArea areaConclusion;
    private javax.swing.JButton btnCrearTabla;
    private javax.swing.JButton btnEjemplo;
    private javax.swing.JButton btnGenerador;
    private javax.swing.JButton btnIngresarDatos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JTextField caja3;
    private javax.swing.JTextField caja4;
    private javax.swing.JTextField caja5;
    private javax.swing.JTextField caja6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton limpiarTablaSimulacion;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    private javax.swing.JTable tabla3;
    private javax.swing.JTable tabla4;
    private javax.swing.JTable tabla5;
    private javax.swing.JTable tabla6;
    private javax.swing.JTable tablaDistribuciones;
    private javax.swing.JTextField textCosto;
    private javax.swing.JTextField textPrecioDescuento;
    private javax.swing.JTextField textPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
