
package actividad_7.tss.codigo.GUI;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.math3.distribution.LogNormalDistribution;
import org.apache.commons.math3.distribution.NormalDistribution;
import org.apache.commons.math3.distribution.TriangularDistribution;

public class VentanaEjercicio2 extends javax.swing.JPanel {

    public VentanaEjercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelEjercicio1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFinal = new javax.swing.JTable();
        btnCrearTabla = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTotales = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        textTotalProfit = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(890, 560));

        PanelEjercicio1.setBackground(new java.awt.Color(102, 102, 102));
        PanelEjercicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelEjercicio1.setPreferredSize(new java.awt.Dimension(1820, 1000));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EJERCICIO 2 - SELECCION DE PROYECTOS");

        jLabel10.setText("-------------------------------------------------");

        jLabel7.setText("TABLA SIMULACION:");

        tablaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proyecto", "Decisiones ", "Ingresos esperados", "Tasa de éxito", "Rendimiento esperado", "Inversión inicial", "Beneficio esperado"
            }
        ));
        jScrollPane2.setViewportView(tablaFinal);

        btnCrearTabla.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCrearTabla.setText("CREAR TABLA");
        btnCrearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaActionPerformed(evt);
            }
        });

        tablaTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PRESUPUESTO", null},
                {"INVERTIDO", null},
                {"EXCEDENTE", null}
            },
            new String [] {
                "DESCRIPCION", "MONTO"
            }
        ));
        jScrollPane4.setViewportView(tablaTotales);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("TOTAL PROFIT");

        javax.swing.GroupLayout PanelEjercicio1Layout = new javax.swing.GroupLayout(PanelEjercicio1);
        PanelEjercicio1.setLayout(PanelEjercicio1Layout);
        PanelEjercicio1Layout.setHorizontalGroup(
            PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textTotalProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(631, Short.MAX_VALUE))
        );
        PanelEjercicio1Layout.setVerticalGroup(
            PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTotalProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(627, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(PanelEjercicio1);
        PanelEjercicio1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaActionPerformed
        Random random = new Random();
        DefaultTableModel model = (DefaultTableModel) tablaFinal.getModel();
        model.setRowCount(0);

        double totalProfit = 0;
        double[] initialInvestments = {250000, 650000, 250000, 250000, 700000, 30000, 350000, 70000};

        for (int i = 0; i < 8; i++) {
            int decision = random.nextInt(2); // 0 o 1
            double expectedRevenue = getRandomRevenue(random);
            double successRate = (random.nextInt(10) + 1) * 0.1; // Valores de 0.1 a 1.0 en pasos de 0.1
            double expectedReturn = expectedRevenue * successRate;
            double initialInvestment = initialInvestments[i]; // Valores predefinidos
            double expectedProfit = (expectedReturn - initialInvestment) * decision;
            totalProfit += expectedProfit;

            model.addRow(new Object[]{i + 1, decision, formatMoney(expectedRevenue), formatPercentage(successRate), formatMoney(expectedReturn), formatMoney(initialInvestment), formatMoney(expectedProfit)});
        }

        tablaFinal.setModel(model);

        // Crear y actualizar tablaTotales
        DefaultTableModel totalModel = (DefaultTableModel) tablaTotales.getModel();
        totalModel.setRowCount(0);

        double fixedValue = 2000000;
        double sumProduct = 0;

        for (int i = 0; i < tablaFinal.getRowCount(); i++) {
            int decision = (int) tablaFinal.getValueAt(i, 1);
            double expectedReturn = Double.parseDouble(tablaFinal.getValueAt(i, 4).toString().replace("$", "").replace(",", ""));
            sumProduct += decision * expectedReturn;
        }

        double finalValue = fixedValue - sumProduct;

        totalModel.addRow(new Object[]{"PRESUPUESTO", formatMoney(fixedValue)});
        totalModel.addRow(new Object[]{"INVERTIDO", formatMoney(sumProduct)});
        totalModel.addRow(new Object[]{"EXCEDENTE", formatMoney(finalValue)});

        tablaTotales.setModel(totalModel);

        // Actualizar textTotalProfit
        textTotalProfit.setText(formatMoney(totalProfit));
    }//GEN-LAST:event_btnCrearTablaActionPerformed

    private double getRandomRevenue(Random random) {
        switch (random.nextInt(4)) {
            case 0: return new NormalDistribution(1000000, 300000).sample();
            case 1: return new TriangularDistribution(500000, 1000000, 1500000).sample();
            case 2: return new LogNormalDistribution(Math.log(1000000), 0.5).sample();
            default: return 500000 + (random.nextDouble() * 1000000); // Uniforme entre 500K y 1.5M
        }
    }

    private String formatMoney(double value) {
        return String.format("$%,.2f", value);
    }

    private String formatPercentage(double value) {
        return String.format("%.0f%%", value * 100);
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEjercicio1;
    private javax.swing.JButton btnCrearTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaFinal;
    private javax.swing.JTable tablaTotales;
    private javax.swing.JTextField textTotalProfit;
    // End of variables declaration//GEN-END:variables
}
