
package actividad_7.tss.codigo.GUI;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
//import org.apache.commons.math3.distribution.NormalDistribution;

public class VentanaEjercicio1 extends javax.swing.JPanel {

    public VentanaEjercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelEjercicio1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEjemplo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFinal = new javax.swing.JTable();
        btnCrearTabla = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTotales = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        textContingencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textTotalFinal = new javax.swing.JTextField();
        btnGeneradorTotales = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(890, 560));

        PanelEjercicio1.setBackground(new java.awt.Color(102, 102, 102));
        PanelEjercicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelEjercicio1.setPreferredSize(new java.awt.Dimension(1820, 1000));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EJERCICIO 4  - ESTIMACION DE COSTOS");

        jLabel10.setText("-------------------------------------------------");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DATOS");

        btnEjemplo.setText("Ejercicio de Ejemplo");
        btnEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemploActionPerformed(evt);
            }
        });

        jLabel7.setText("TABLA SIMULACION:");

        tablaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Gestion de Proyecto", "", "Gestion de ingenieria", null, "Diseño definitivo", null, "Gestion de constr WHC", null, "Administracion de Inicio", null, "Gestion ambiental", null},
                {"", "", "Estudios tecnicos", null, "Adquisisciones", null, "Modifi entre granjas", null, "Soporte de Inicio", null, "Seguridad", null},
                {null, "", "Diseño definitivo", null, "Fabricacion", null, "Modif entre granjas C", null, "Rev de prep para inicio", null, "NEPA", null},
                {null, null, "Inspeccion de ingenieria", null, "", null, "Modif en granjas AY", null, null, null, "RCRA", null},
                {null, "", "Dsñ de retiro de equipos", null, null, null, "Adquisicion de gastos", null, null, null, "CAA", null},
                {"", null, "", null, "", null, "Preparacion de instalaciones", null, null, null, "", null},
                {null, null, null, null, null, null, "Servicios de Const.", null, null, null, null, null},
                {"Admin. proyecto", null, "Total Ingenieria", null, "Total CENRTC", null, "Total Construccion", "", "Total otros costos", null, "Total Seguridad y ambiente", null},
                {"Rango Min", null, "Rango Min", null, "Rango Min", null, "Rango Min", null, "Rango Min", null, "Rango Min", null},
                {"Rango Max", null, "Rango Max", null, "Rango Max", null, "Rango Max", null, "Rango Max", null, "Rango Max", null},
                {"Simulado", null, "Simulado", null, "Simulado", null, "Simulado", null, "Simulado", "", "Simulado", null}
            },
            new String [] {
                "Descripcion", "Estimado", "Descripcion", "Estimado", "Descripcion", "Estimado", "Descripcion", "Estimado", "Descripcion", "Estimado", "Descripcion", "Estimado"
            }
        ));
        jScrollPane2.setViewportView(tablaFinal);

        btnCrearTabla.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCrearTabla.setText("CREAR TABLA");
        btnCrearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTablaActionPerformed(evt);
            }
        });

        tablaTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"GESTION DEL PROYECTO", null},
                {"INGENIERIA", null},
                {"CENRTC", null},
                {"CONSTRUCCION", null},
                {"COSTOS ADMINISTRATIVOS", null},
                {"NORMAS Y SEGURIDAD AMBIENTAL", null},
                {"TOTAL", null},
                {"MIN", null},
                {"MAX", null},
                {"SIMULADO", null}
            },
            new String [] {
                "DESCRIPCION", "MONTO"
            }
        ));
        jScrollPane4.setViewportView(tablaTotales);

        jLabel11.setText("Contingencia:");

        jLabel6.setBackground(new java.awt.Color(102, 153, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("GESTION DEL PROYECTO");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setBackground(new java.awt.Color(102, 153, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INGENIERIA");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setBackground(new java.awt.Color(102, 153, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CENRTC");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setBackground(new java.awt.Color(102, 153, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CONSTRUCCION");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setBackground(new java.awt.Color(102, 153, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("COSTOS ADMINISTRATIVOS");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setBackground(new java.awt.Color(102, 153, 255));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("NORMAS Y SEGURIDAD AMBIENTAL");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("TOTAL CON CONTINGENCIA");

        btnGeneradorTotales.setText("Generar tabla de Totales");
        btnGeneradorTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneradorTotalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEjercicio1Layout = new javax.swing.GroupLayout(PanelEjercicio1);
        PanelEjercicio1.setLayout(PanelEjercicio1Layout);
        PanelEjercicio1Layout.setHorizontalGroup(
            PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textContingencia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10))
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnEjemplo))
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnGeneradorTotales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(44, 44, 44)
                                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        PanelEjercicio1Layout.setVerticalGroup(
            PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjemplo)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)))
                .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGeneradorTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelEjercicio1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(PanelEjercicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textContingencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(btnCrearTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(438, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(PanelEjercicio1);
        PanelEjercicio1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTablaActionPerformed
        int filasSumar = 7; // Hasta la fila 7 (índice 6 en base 0)
        int filaResultado = 7; // Fila donde se colocará el resultado (índice 7 en base 0)
        int columnas = tablaFinal.getColumnCount();

        for (int col = 1; col < columnas; col += 2) { // Iterar solo columnas pares
            int suma = 0;
            for (int fila = 0; fila < filasSumar; fila++) {
                Object valor = tablaFinal.getValueAt(fila, col);
                if (valor != null) {
                    if (valor instanceof Number) {
                        suma += ((Number) valor).intValue();
                    } else {
                        try {
                            suma += Integer.parseInt(valor.toString().replace("$", "").replace(",", ""));
                        } catch (NumberFormatException e) {
                            // Ignorar valores no numéricos
                        }
                    }
                }
            }
            tablaFinal.setValueAt(suma, filaResultado, col); // Colocar suma en la fila 8
        }
    }//GEN-LAST:event_btnCrearTablaActionPerformed

    private void btnEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemploActionPerformed
        int[][] valores = {
            {0, 4719278, 0, 1344586, 0, 668990, 0, 4976687, 0, 1676355, 0, 424013},
            {0, 0, 0, 479725, 0, 632731, 0, 1307065, 0, 1944661, 0, 3579477},
            {0, 0, 0, 10575071, 0, 902498, 0, 6602884, 0, 1042521, 0, 64106},
            {0, 0, 0, 5007916, 0, 0, 0, 1636429, 0, 0, 0, 11474},
            {0, 0, 0, 2561272, 0, 0, 0, 4054629, 0, 0, 0, 176869},
            {0, 0, 0, 0, 0, 0, 0, 9536165, 0, 0, 0, 0},
            {0, 0, 0, 0, 0, 0, 0, 7041973, 0, 0, 0, 0}
        };

        for (int fila = 0; fila < valores.length; fila++) {
            for (int col = 1; col < valores[fila].length; col += 2) {
                if (valores[fila][col] != 0) {
                    tablaFinal.setValueAt(valores[fila][col], fila, col);
                }
            }
        }
        textContingencia.setText("20");
    }//GEN-LAST:event_btnEjemploActionPerformed

    private void btnGeneradorTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneradorTotalesActionPerformed
        int filaFuente = 7;  // Fila de donde tomamos los valores (índice 7 en base 0)
        int filaDestinoResta = 8;  // Fila donde colocaremos los resultados de la resta (índice 8 en base 0)
        int filaDestinoSuma = 9;   // Fila donde colocaremos los resultados de la suma (índice 9 en base 0)
        int filaDestinoRandom = 10; // Fila donde colocaremos el número aleatorio (índice 9 en base 0)
        int columnas = tablaFinal.getColumnCount();

        for (int col = 1; col < columnas; col += 2) { // Iterar solo columnas pares
            Object valorObj = tablaFinal.getValueAt(filaFuente, col);
            if (valorObj != null) {
                try {
                    double ultimoValor = Double.parseDouble(valorObj.toString().replace("$", "").replace(",", ""));
                    int valor = (int) ultimoValor;
                    int base;

                    if (valor >= 1_000_000) {
                        base = 100_000;
                    } else if (valor >= 100_000) {
                        base = 10_000;
                    } else if (valor >= 10_000) {
                        base = 1_000;
                    } else {
                        base = 100;
                    }

                    int maxRandom = Math.max(base, valor / 4);
                    int randomValue = (int) (Math.random() * (maxRandom - base + 1)) + base;

                    // Calcular resultados
                    int resultadoResta = valor - randomValue;
                    int resultadoSuma = valor + randomValue;

                    // Colocar los resultados en la tabla
                    tablaFinal.setValueAt(resultadoResta, filaDestinoResta, col);
                    tablaFinal.setValueAt(resultadoSuma, filaDestinoSuma, col);

                    // Generar número aleatorio entre los valores de la fila 8 y fila 9
                    int minRange = Math.min(resultadoResta, resultadoSuma);
                    int maxRange = Math.max(resultadoResta, resultadoSuma);
                    int randomBetween = (int) (Math.random() * (maxRange - minRange + 1)) + minRange;

                    // Colocar el número aleatorio en la fila 10
                    tablaFinal.setValueAt(randomBetween, filaDestinoRandom, col);
                    
                    llenarOtraTabla();

                } catch (NumberFormatException e) {
                    System.err.println("Error al convertir el valor en la columna " + col + ": " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnGeneradorTotalesActionPerformed
    
    private void llenarOtraTabla(){
        int filaFuente = 10;  // Fila de donde tomamos los valores en tablaFinal (fila 10 en base 0)
        int filaDestinoInicial = 0; // Fila inicial en tablaTotales (fila 6 en base 0)
        int columnas = tablaFinal.getColumnCount();

        int filaDestinoTablaTotales = filaDestinoInicial; // Usamos una variable independiente

        // Paso 1: Transferir valores de tablaFinal (col. pares, fila 10) a tablaTotales (col. 2)
        for (int col = 1; col < columnas; col += 2) { 
            Object valorObj = tablaFinal.getValueAt(filaFuente, col);
            if (valorObj != null) {
                try {
                    int valor = Integer.parseInt(valorObj.toString().replace("$", "").replace(",", ""));

                    // Guardamos el valor en la fila correspondiente de tablaTotales
                    tablaTotales.setValueAt(valor, filaDestinoTablaTotales, 1);

                    // Incrementamos la fila destino para la siguiente iteración
                    filaDestinoTablaTotales++;

                } catch (NumberFormatException e) {
                    System.err.println("Error al convertir el valor en la columna " + col + ": " + e.getMessage());
                }
            }
        }

        // Paso 2: Sumar filas 1 a 6 en tablaTotales, columna 2 y colocarlo en la fila 7
        int sumaTotal = 0;
        for (int fila = 0; fila < 6; fila++) { 
            Object valorObj = tablaTotales.getValueAt(fila, 1);
            if (valorObj != null) {
                try {
                    sumaTotal += Integer.parseInt(valorObj.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Error al sumar fila " + (fila + 1) + ": " + e.getMessage());
                }
            }
        }
        tablaTotales.setValueAt(sumaTotal, 6, 1);

        // Paso 3: Evaluar el valor de la fila 7 y calcular fila 8 (resta) y fila 9 (suma)
        int base;
        if (sumaTotal >= 1_000_000) {
            base = 100_000;
        } else if (sumaTotal >= 100_000) {
            base = 10_000;
        } else if (sumaTotal >= 10_000) {
            base = 1_000;
        } else {
            base = 100;
        }

        int maxRandom = Math.max(base, (int) sumaTotal / 4);
        int randomValue = (int) (Math.random() * (maxRandom - base + 1)) + base;

        int resultadoResta = sumaTotal - randomValue;
        int resultadoSuma = sumaTotal + randomValue;

        tablaTotales.setValueAt(resultadoResta, 7, 1); // Fila 8
        tablaTotales.setValueAt(resultadoSuma, 8, 1); // Fila 9

        // Paso 4: Generar número aleatorio entre fila 8 y fila 9, colocar en fila 10
        int minRange = (int) Math.min(resultadoResta, resultadoSuma);
        int maxRange = (int) Math.max(resultadoResta, resultadoSuma);
        int randomBetween = (int) (Math.random() * (maxRange - minRange + 1)) + minRange;

        tablaTotales.setValueAt(randomBetween, 9, 1); // Fila 10

        // Paso 5: Calcular textTotalFinal usando textContingencia y fila 10 de tablaTotales
        try {
            int valorFila10 = Integer.parseInt(tablaTotales.getValueAt(9, 1).toString());
            double porcentajeContingencia = Double.parseDouble(textContingencia.getText()) / 100.0;
            int totalFinal = valorFila10 + (int)(valorFila10 * porcentajeContingencia);

            textTotalFinal.setText("   Bs. " + totalFinal);
        } catch (NumberFormatException e) {
            System.err.println("Error al calcular el total final: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEjercicio1;
    private javax.swing.JButton btnCrearTabla;
    private javax.swing.JButton btnEjemplo;
    private javax.swing.JButton btnGeneradorTotales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tablaFinal;
    private javax.swing.JTable tablaTotales;
    private javax.swing.JTextField textContingencia;
    private javax.swing.JTextField textTotalFinal;
    // End of variables declaration//GEN-END:variables
}
